services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow-container
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-container:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres-container:5432/airflow
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt/ecommerce:/opt/dbt
      - ./.dbt/profiles.yml:/home/airflow/.dbt/profiles.yml
      - ./logs:/opt/airflow/logs
      - ./kaggle.json:/home/airflow/.kaggle/kaggle.json:ro
      - ./datasets:/opt/airflow/datasets
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow scheduler & airflow webserver"

  postgres:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
